ARG ARCH
FROM $ARCH/alpine:latest

ARG QEMU_BIN
COPY $QEMU_BIN /usr/bin

WORKDIR /

RUN mkdir -p conf && \
	mkdir -p data

RUN apk update && \
	apk add --no-cache tzdata bash aria2 darkhttpd s6

ADD aria2-files/ /conf/

ADD AriaNg/ /AriaNg/

RUN chmod +x /conf/start.sh

RUN touch /conf/session.dat && \
	touch /conf/dht.dat && \
	touch /conf/dht6.dat && \
    touch /conf/logs.txt

VOLUME ["/data"]

EXPOSE 6800
EXPOSE 6801

CMD ["/conf/start.sh"]